package com.turreta.wsdl.webservicex.geoipservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-08-26T12:22:16.466-07:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://www.dataaccess.com/webservicesserver/", name = "NumberConversionSoapType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NumberConversionSoapType {

    /**
     * Returns the word corresponding to the positive number passed as parameter. Limited to quadrillions.
     */
    @WebMethod(operationName = "NumberToWords")
    @WebResult(name = "NumberToWordsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", partName = "parameters")
    public NumberToWordsResponse numberToWords(

        @WebParam(partName = "parameters", name = "NumberToWords", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        NumberToWords parameters
    );

    /**
     * Returns the non-zero dollar amount of the passed number.
     */
    @WebMethod(operationName = "NumberToDollars")
    @WebResult(name = "NumberToDollarsResponse", targetNamespace = "http://www.dataaccess.com/webservicesserver/", partName = "parameters")
    public NumberToDollarsResponse numberToDollars(

        @WebParam(partName = "parameters", name = "NumberToDollars", targetNamespace = "http://www.dataaccess.com/webservicesserver/")
        NumberToDollars parameters
    );
}
